import { LIVE } from '../config';
import { buildTube } from '../mock/tube';
import type { TubeNetwork, TubeStation } from '../types';

interface Snapshot {
  generated: string;
  lines: Array<{ id: string; name: string; color: string; mode: string }>;
  stations: Array<{ id: string; name: string; lat: number; lon: number }>;
  hops: Array<{ line: number; a: number; b: number; minutes: number; geom?: [number, number][] }>;
}

let cached: Promise<TubeNetwork> | null = null;

/**
 * Live mode: the committed TfL snapshot (generated by scripts/fetch-tfl.mjs —
 * real lines, stations and distance-derived hop times; no TfL key needed at
 * runtime). Mock mode: the 4-line procedural network.
 */
export function loadTubeNetwork(): Promise<TubeNetwork> {
  if (!cached) {
    cached = LIVE
      ? import('../../data/tfl-network.json').then((m) => fromSnapshot(m.default as unknown as Snapshot))
      : Promise.resolve(buildTube());
  }
  return cached;
}

function fromSnapshot(snap: Snapshot): TubeNetwork {
  const stations: TubeStation[] = snap.stations.map((s) => ({
    id: s.id,
    name: s.name,
    pos: [s.lon, s.lat],
    lines: [],
  }));
  for (const h of snap.hops) {
    const lineId = snap.lines[h.line].id;
    for (const si of [h.a, h.b]) {
      if (!stations[si].lines.includes(lineId)) stations[si].lines.push(lineId);
    }
  }
  return {
    lines: snap.lines.map((l) => ({
      id: l.id,
      name: l.name,
      color: l.color,
      mode: l.mode as TubeNetwork['lines'][number]['mode'],
    })),
    stations,
    hops: snap.hops,
    stationIndex: new Map(stations.map((s, i) => [s.id, i])),
  };
}

/** [name, colour, method] triples for the in-panel legend */
export async function loadTransitLegend(): Promise<Array<[string, string, string]>> {
  const tube = await loadTubeNetwork();
  return tube.lines.map((l) => [l.name, l.color, l.mode]);
}
